apiVersion: v1
kind: Service
metadata:
  name: gamebot
  labels:
    name: gamebot    
spec:
  selector:
    name: gamebot    
  type: LoadBalancer
  ports:
   - port: 80
     name: gamebot
     targetPort: 8080
     protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamebot
spec:
  replicas: 3
  selector:
    matchLabels:
      name: gamebot      
  minReadySeconds: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: gamebot        
    spec:
      # imagePullSecrets:
      #   - name: teamregistry
      containers:
      - name: gamebot
        image: ghcr.io/azure-adventure-day/azure-adventure-day-coach/gamebot:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: gamebot         
            protocol: TCP
        env: 
          - name: "PORT"
            value: "8080"
          - name: "PICK_STRATEGY"
            value: "RANDOM"
          - name: "APPINSIGHTS_INSTRUMENTATIONKEY"
            value: "0138e6ef-3f0b-48ed-8040-19aa2a1a570d"
          - name: "FF_BETS"
            value: "1"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
